export {default as Activity} from './activity.png';
export { default as LogoImg } from './logo.png';
export { default as Avatar } from './avatar.svg';
export { default as Comments } from './comments.svg';
export { default as Home } from './home.png';
export { default as Like } from './like.svg';
export { default as AddPhoto } from './photo.png';
export { default as Pin } from './pin.png';
export { default as Profile } from './profile.png';
export { default as Sample } from './sample.jpeg';
export { default as Search } from './search.png';
export { default as HashIcon } from './hash.svg';
export { default as Back } from './back.svg';